### ISSUE TITLE
Cloud not use target_folder with root target

### ISSUE THREAD

**Issue by guiadco** [seanmiddleditch/gha-publish-to-git#6]
If i try to upload to root target folder, i have error: `not a git repository`

**Comment by DmitrijOkeanij** [comment]
The same for me.
Did you find a solution?

**Comment by guiadco** [comment]
Hi,

Waiting for an answer or update, i use another action.

If the maintainer make the necessary, i will use this one again, or i will do the PR when i have time.

**Comment by seanmiddleditch** [comment]
I think one of the recently-merged PRs addresses this; I was accidentally deleting the `.git` folder if the target was the root of the git repo. Can you retry?

**Comment by guiadco** [comment]
yes for me it's ok
