### ISSUE TITLE
Opt out of failing action when nothing to commit

### ISSUE THREAD

**Issue by garethr** [seanmiddleditch/gha-publish-to-git#9]
Currently, if git reports than their is nothing to commit the action fails.

```
nothing to commit, working tree clean
```

This probably makes sense for some use cases, but not in my case unfortunately. 

For me I'm generating files on changes to specific files in the repo. But not all pushes will cause the generated files to change (for instance changes to tests or documentation). In these cases I'd like the action to run and report success vs the current behaviour of failing. 

Would it be possible to add a parameter to opt in to this behaviour?

**Comment by antfu** [comment]
Would like to see this implemented too.
